services:
  postgres:
    image: postgres:16-alpine
    container_name: docker-postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=learnmatedb
    ports:
      - "5050:5432"
  learnmate:
    image: learnmate-backend
    container_name: c-learnmate-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/learnmatedb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - postgres
    ports:
      - "8080:8080"
