services:
  db:
    image: postgres:16-alpine
    container_name: docker-postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=learnmatedb
    ports:
      - "5050:5432"
